### ISSUE TITLE
Pay for app complete / dead account window Ultimate Downloader

### ISSUE THREAD

**Issue by naylormon** [keshavbhatt/ultimate-media-download-linux#1]
![udma](https://user-images.githubusercontent.com/115770971/195767380-07e9f631-71c9-4f1f-a271-8b361b83a01a.png)
After paying for the lifetime package, I pushed the appropriate button but nothing happens.
Great app. I didn't use it for a couple of days and when I came back I paid a couple days after the program was locked. Hope that helps!
Please let me know how I might resolve this seemingly simple issue.

Thanks!

**Comment by keshavbhatt** [comment]
> how I might resolve this seemingly simple issue
Hi, may I know what the exact issue is?
Your account is active as shown in the screenshot above. Please look for **Account type** in the above shared picture, It says **Pro**. All feature are active now. Restore Purchase and Purchase License button are disabled cause you don't need to press them now. You already purchased license and your license is already active so make so sense to restore it.

**Comment by naylormon** [comment]
Hello sir,
I removed and re-installed the program on the machine I installed it on. The features are working now and it is great. Thank you for getting back to me Keshav.  I am a new Ubuntu user of a few years. My lack of experience is sometimes embarrassing.
Thank you so much!!
